# Generated by Django 4.2 on 2023-05-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
